### ISSUE TITLE
Can you provide a YOLOv5 pig detection model，using for paper testing comparison 

### ISSUE THREAD

**Issue by mengjiexu** [SSTato/Pig-count#3]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Now I write paper for pig counting, and need the detect model to run this project for testing comparison.
Can you provide a small pig detection model?
Thanks very much

**Comment by SSTato** [comment]
I forgot which one is, you can test it yourself. It's been too long.
https://www.aliyundrive.com/t/2NNRuebb2YmPVxsavZV2
