### ISSUE TITLE
你好，可以更新下数据链接吗，失效了，感谢先~

### ISSUE THREAD

**Issue by ws-zhongm** [SSTato/Pig-count#4]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

你好，可以更新下数据链接吗，失效了，感谢先~

**Comment by SSTato** [comment]
阿里云盘已经无法公开分享文件，创建的链接只能一天一人访问，太麻烦了。 https://www.alipan.com/t/ML5DXkRPyR50BGWnjuYr

**Comment by ws-zhongm** [comment]
链接可以使用，感谢~
